version: "3.4"

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    expose:
      - 27017
  app:
    build:
      context: .
      target: production
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/scoring-api?retryWrites=true&w=majority
      TOKEN_SECRET: $TOKEN_SECRET
    command: node --use_strict src/index.js
  test:
    build:
      context: .
      target: test
    depends_on:
      - mongo
      - app
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo/booksdb?retryWrites=true&w=majority
      TOKEN_SECRET: $TOKEN_SECRET
    command: npm test
    volumes:
      - ./:/app
