openapi: 3.0.0
info:
  title: Scoring API
  description: Optional multi-line or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /healthcheck/ping:
    get:
      description: Returns the readiness of the service
      operationId: ping
      x-eov-operation-id: ping
      x-eov-operation-handler: healthcheck
      parameters:
        - $ref: "#/components/parameters/x-correlation-id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /apiKey:
    get:
      description: Get a new API key
      operationId: getApiKey
      x-eov-operation-id: getApiKey
      x-eov-operation-handler: apiKey
      parameters:
        - $ref: "#/components/parameters/x-team-id"
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getApiKeyResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /team:
    post:
      description: Create a new team
      operationId: createTeam
      x-eov-operation-id: createTeam
      x-eov-operation-handler: team
      requestBody:
        description: team schema
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postTeamSchema"
      responses:
        "201":
          description: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    get:
      description: Get your team info
      operationId: getTeam
      x-eov-operation-id: getTeam
      x-eov-operation-handler: team
      security:
        - verifyApiKey: []
      parameters:
        - $ref: "#/components/parameters/apiKey"
      responses:
        "200":
          description: team info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTeamsResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    put:
      description: Get all the teams
      operationId: putTeam
      x-eov-operation-id: putTeam
      x-eov-operation-handler: team
      security:
        - verifyApiKey: []
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTeamsResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    delete:
      description: Get all the teams
      operationId: deleteTeam
      x-eov-operation-id: deleteTeam
      x-eov-operation-handler: team
      security:
        - verifyApiKey: []
      responses:
        "204":
          description: team deletion confirmation
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /team/{teamId}:
    put:
      description: put team
      operationId: putTeam
      x-eov-operation-id: putTeam
      x-eov-operation-handler: putTeam
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: Numeric ID of the team to get
      responses:
        "200":
          description: Successful PUT response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/putTeamResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /user:
    post:
      description: Create a new user
      operationId: createUser
      x-eov-operation-id: createUser
      x-eov-operation-handler: user
      requestBody:
        description: user schema
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postUserSchema"
      responses:
        "201":
          description: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    get:
      description: Get all the users for a team
      operationId: getUser
      x-eov-operation-id: getUser
      x-eov-operation-handler: user
      parameters:
        - $ref: "#/components/parameters/teamName"
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getUsersResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /sign-s3:
    get:
      description: get signed Url
      operationId: getS3SignedUrl
      x-eov-operation-id: getS3SignedUrl
      x-eov-operation-handler: s3
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          allowReserved: true
          description: File name
        - in: query
          name: filetype
          schema:
            type: string
          allowReserved: true
          description: File type
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getS3SignedUrlResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /account:
    get:
      description: Account
      operationId: getAccount
      x-eov-operation-id: getAccount
      x-eov-operation-handler: account
      responses:
        "200":
          description: account page
          content:
            text/html:
              schema:
                type: string
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  securitySchemes:
    verifyApiKey:
      type: apiKey
      in: header
      name: x-api-key
  responses:
    "401":
      description: Unauthorised Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorisedError"
    "404":
      description: Not Found Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundError"
    "500":
      description: Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerError"
    default:
      description: Invalid Request Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidRequestError"
  parameters:
    x-team-id:
      name: x-team-id
      description: team id for an existing team
      in: header
      required: true
      schema:
        type: string
    x-correlation-id:
      name: x-correlation-id
      required: true
      in: header
      description: Correlation ID required for log tracing.
      schema:
        type: string
        format: uuid
    apiKey:
      name: x-api-key
      required: true
      in: header
      description: api key
      schema:
        type: string
        additionalProperties: false
    teamName:
      name: teamId
      in: query
      required: true
      schema:
        type: string
        example: Team America
  schemas:
    getS3SignedUrlResponse:
      description: S3 signed URL response
      type: object
      additionalProperties: false
      required:
        - signedRequest
        - url
      properties:
        signedRequest:
          type: string
        url:
          type: string
    getApiKeyResponse:
      description: new api key response
      type: object
      properties:
        apiKey:
          type: string
          pattern: '[a-zA-Z0-9\b]{32}$' # This is set in constants
    getUsersResponse:
      description: get users from a team
      type: array
      items:
        $ref: "#/components/schemas/userSchema"
    getTeamsResponse:
      $ref: "#/components/schemas/teamSchema"
    postTeamSchema:
      description: team schema
      type: object
      additionalProperties: false
      required:
        - teamName
      properties:
        teamName:
          type: string
    putTeamResponse:
      $ref: "#/components/schemas/teamSchema"
    teamSchema:
      description: team schema
      type: object
      properties:
        teamName:
          type: string
        teamId:
          type: string
    postUserSchema:
      description: user schema
      type: array
      items:
        type: object
        required:
          - firstName
          - lastName
          - email
        properties:
          firstName:
            type: string
          lastName:
            type: string
          email:
            type: string
          teamName:
            type: string
            nullable: true
    userSchema:
      description: user schema
      type: object
      properties:
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        teamName:
          type: string
    healthCheckResponse:
      description: healthcheck OK response
      type: object
      properties:
        message:
          type: string
          enum:
            - OK
    NotFoundError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    UnauthorisedError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InvalidRequestError:
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InternalServerError:
      title: Internal Server Error
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
