openapi: 3.0.0
info:
  title: Scoring API
  description: Optional multi-line or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /healthcheck/ping:
    get:
      description: Returns the readiness of the service
      operationId: ping
      x-eov-operation-id: ping
      x-eov-operation-handler: healthcheck
      parameters:
        - $ref: "#/components/parameters/x-correlation-id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /team:
    post:
      description: Create a new team
      operationId: createTeam
      x-eov-operation-id: createTeam
      x-eov-operation-handler: team
      requestBody:
        description: team schema
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postTeamSchema"
      responses:
        "201":
          description: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    get:
      description: Get all the teams
      operationId: getTeam
      x-eov-operation-id: getTeam
      x-eov-operation-handler: team
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTeamsResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    put:
      description: Get all the teams
      operationId: putTeam
      x-eov-operation-id: putTeam
      x-eov-operation-handler: team
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTeamsResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    delete:
      description: Get all the teams
      operationId: deleteTeam
      x-eov-operation-id: deleteTeam
      x-eov-operation-handler: team
      responses:
        "204":
          description: team deletion confirmation
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /user:
    post:
      description: Create a new user
      operationId: createUser
      x-eov-operation-id: createUser
      x-eov-operation-handler: user
      requestBody:
        description: user schema
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postUserSchema"
      responses:
        "201":
          description: OK
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    get:
      description: Get all the users for a team
      operationId: getUser
      x-eov-operation-id: getUser
      x-eov-operation-handler: user
      parameters:
        - $ref: "#/components/parameters/teamName"
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getUsersResponse"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  responses:
    "401":
      description: Unauthorised Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorisedError"
    "404":
      description: Not Found Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundError"
    "500":
      description: Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerError"
    default:
      description: Invalid Request Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidRequestError"
  parameters:
    x-correlation-id:
      name: x-correlation-id
      required: true
      in: header
      description: Correlation ID required for log tracing.
      schema:
        type: string
        format: uuid
    teamName:
      name: teamId
      in: query
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    getUsersResponse:
      description: get users from a team
      type: array
      items:
        $ref: "#/components/schemas/userSchema"
    getTeamsResponse:
      description: get teams response
      type: array
      items:
        $ref: "#/components/schemas/teamSchema"
    postTeamSchema:
      description: team schema
      type: object
      properties:
        teamName:
          type: string
    teamSchema:
      description: team schema
      type: object
      properties:
        teamName:
          type: string
        teamId:
          type: string
          format: uuid
    postUserSchema:
      description: user schema
      type: array
      items:
        type: object
        properties:
          firstName:
            type: string
          lastName:
            type: string
          email:
            type: string
          teamName:
            type: string
    userSchema:
      description: user schema
      type: object
      properties:
        userId:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        teamName:
          type: string
    healthCheckResponse:
      description: healthcheck OK response
      type: object
      properties:
        message:
          type: string
          enum:
            - OK
    NotFoundError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    UnauthorisedError:
      title: Not Found Error
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InvalidRequestError:
      additionalProperties: false
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
    InternalServerError:
      title: Internal Server Error
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: string
